language: cpp
sudo: false
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libtool
    - libexpat1-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libgeos-dev
    - libgeos++-dev
    - libpq-dev
    - libbz2-dev
    - libproj-dev
    - lua5.2
    - liblua5.2-dev
    - libboost1.55-dev
    - libboost-system1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-thread1.55-dev
matrix:
  include:
    - os: linux
      compiler: clang
      env: BUILDCXXFLAGS='-Werror -pedantic -Wall -std=c++11'
    - os: linux
      compiler: gcc
      env: BUILDCXXFLAGS='-Werror -pedantic -Wall -std=c++11'
    - os: osx
      compiler: clang
      env: BUILDCXXFLAGS='-pedantic -Wall -std=c++11'
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew install protobuf lua;
    fi
# update versions
install:
  - if [[ $CC == 'gcc' ]]; then
      export CC=gcc-4.8;
    fi
  - if [[ $CXX == 'g++' ]]; then
      export CXX=g++-4.8;
    fi
before_script:
  - export CXXFLAGS="-Werror"
  - $CXX --version
  - xml2-config --version
  - geos-config --version
  - proj | head -n1
  - lua -v
script:
  - ./autogen.sh
  - ./configure
  - make -j2 check TESTS='' CXXFLAGS="$BUILDCXXFLAGS"
after_failure:
  - cat config.log
  # rerun make, but verbosely
  - make check TESTS='' V=1 CXXFLAGS="$BUILDCXXFLAGS"
